---
creation_rules:
  - path_regex: clusters/.*\.sops\.ya?ml
    encrypted_regex: "(^(users.*)$)|(network_token.*)"
    key_groups:
      - age:
          - age13srthcdyr08hp7w5xvezn5fex4p5kw7tky2pnrfef2u4j3uqsqgqwak9gc

